---
title: "Whats Cooking"
format: pdf
editor: visual
---

# Load libraries

```{r}
library(tidyverse)
library(tidymodels)
library(vroom)
library(dplyr)
library(tune)
library(ggplot2)
library(embed)
library(doParallel)
library(kknn)
library(discrim)
library(remotes)
library(jsonlite)
```

# Read Data

```{r}
trainSet <- read_file("C:/Users/User/OneDrive - Brigham Young University/Fall 2025/STAT 348/whats-cooking/train.json/train.json") %>% 
  fromJSON()
testSet <- read_file("C:/Users/User/OneDrive - Brigham Young University/Fall 2025/STAT 348/whats-cooking/test.json/test.json") %>%
  fromJSON()
```

# Cleaning

```{r}
trainSet <- trainSet %>%
  mutate(
    # feature 1: number of ingredients
    n_ingredients = map_int(ingredients, length),

    # feature 2: average ingredient name length
    avg_ing_length = map_dbl(ingredients, ~ mean(str_length(.x))),

    # feature 3: any rice in the recipe?
    has_rice = map_int(ingredients, ~ any(str_detect(.x, "rice"))),

    # text column for tokenization (space-separated ingredients)
    ingredients_text = map_chr(ingredients, ~ paste(.x, collapse = " "))
  )

testSet <- testSet %>%
  mutate(
    n_ingredients = map_int(ingredients, length),
    avg_ing_length = map_dbl(ingredients, ~ mean(str_length(.x))),
    has_rice = map_int(ingredients, ~ any(str_detect(.x, "rice"))),
    ingredients_text = map_chr(ingredients, ~ paste(.x, collapse = " "))
  )

```

# Recipe

```{r}
library(textrecipes)
rec <- recipe(cuisine ~ ingredients_text + n_ingredients + avg_ing_length + has_rice,
              data = trainSet) %>%
  step_tokenize(ingredients_text) %>%
  step_tokenfilter(ingredients_text, max_tokens = 1000) %>%  # keep vocab small
  step_tf(ingredients_text) %>%
  step_normalize(all_numeric_predictors())
```

# simple model

```{r}


# 2. Model spec (multinomial regression for classification)
cuisine_model <- multinom_reg(mode = "classification") %>% 
  set_engine("nnet", MaxNWts = 100000, trace = FALSE)

# 3. Workflow
wf <- workflow() %>% 
  add_model(cuisine_model) %>% 
  add_recipe(recipe)

# 4. Fit on trainSet
wf_fit <- wf %>% 
  fit(data = trainSet)

# 5. Predict classes for testSet
test_pred_class <- predict(wf_fit, new_data = testSet, type = "class")

# 6. Kaggle submission: id + predicted cuisine
submission <- testSet %>% 
  select(id) %>% 
  mutate(cuisine = test_pred_class$.pred_class)

write_csv(submission, "submission.csv")

```

# Random forest

```{r}
cuisine_model <- rand_forest(trees = 500) %>%
  set_mode("classification") %>%
  set_engine("ranger", importance = "impurity")

wf <- workflow() %>%
  add_model(cuisine_model) %>%
  add_recipe(rec)

wf_fit <- wf %>%
  fit(data = trainSet)

test_pred_class <- predict(wf_fit, new_data = testSet, type = "class")

submission <- tibble(
  id      = testSet$id,
  cuisine = test_pred_class$.pred_class
)

write_csv(submission, "submission_rf_tfidf.csv")

```

in tuning grid add argument control(save pred = true, verbosen
